Popup window
DamenaM/Mobile-Menu pull request #3
Opened 2023-01-06 07:55 UTC by DamenaM

### PR for the details popup window

- [ ] clicks (or taps) the button to check project details, and the popup with details about the project appears.
- [ ] clicks (or taps) the close (X) button, and the popup disappears.
- [ ] JavaScript array to store all of the information for all projects.
- [ ] config linter

2023-01-06 10:02 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @DamenaM    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔️ Professional PR. 👍
✔️ Professional Readme. 👍

## Required Changes ♻️


- [ ] **Check the comments below 👇**


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 10:02 UTC, TuyishimireEric commented on style.css
> +}
## Popup window styling ♻️ 

- [ ] Good job on implementing the popup window with dynamic data 👍 👍 but  I think it would be better to improve the styling to replicate the original design 😎😎

    - It would be better to add a ```fixed``` and ```blurred``` container behind the window for the best user experience and this will focus the user's attention on the pop-up window and the content it contains. When the rest of the page is blurred, it can make the pop-up window stand out more, which can help the user understand that it is a separate, distinct element. 👍 👍 

   You may follow this [link](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur) for more info 

    - it would be better also to adjust the margin of your window in the center of the page to replicate the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=pdQWa6stPBCK7HQA-0) this will 
    
   For example: 
```
.popup {
    background-color: #fff;
    position: fixed;
    top: 50%;
    left: 50%;
    transition: 200ms ease-in-out;
    transform: translate(-50%, -50%) scale(0);
    border-radius: 14px;
    z-index: 10;
    background-color: #fff;
    width: 80%;
    height: 90%;
    padding: 12px;
    overflow: scroll;
}
```


### Your design
![image](https://user-images.githubusercontent.com/102757126/210975088-c9edd751-39ab-4fd4-be85-f6ceb8ab576a.png)

### Figma design
![image](https://user-images.githubusercontent.com/102757126/210975155-dbdd83c6-47c2-4176-808d-e1661a7f008b.png)


- [ ]  Kindly Make sure that the popup follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, text, margins). 🙏

2023-01-06 10:02 UTC, TuyishimireEric commented on style.css
> +}
- [ ] I think it would be better to adjust the width and height for **popup img** to replicate the Figma design 👍 

    _Remember As a developer, it's important to **replicate a design** provided by a designer or design team because it helps ensure that the final product aligns with the intended visual and user experience. Designs provide a clear direction for the look and feel of the product, and it's the developer's job to implement those designs accurately and efficiently. 😉😉_

2023-01-06 10:02 UTC, TuyishimireEric commented on style.css
> +}
- [ ]  I think it would be better also to remove the default generated point of ```<ul>``` tag by adding in CSS ```list-style-type: none;``` and try to replicate the given separator on Figma design on both **desktop and mobile version** 😎😎

### Your design 
![image](https://user-images.githubusercontent.com/102757126/210976508-4b3e638c-0915-450e-81d5-333589b30826.png)

### Figma design
![image](https://user-images.githubusercontent.com/102757126/210976664-ce6f56e1-38a0-4c39-a8f1-cd395992db1d.png)

2023-01-06 10:02 UTC, TuyishimireEric commented on style.css
> +}
- [ ] It would be better also to adjust popup lang buttons by reducing the space between them on your mobile version and also by adjusting their background to replicate the Figma design 👍 

### Your design
![image](https://user-images.githubusercontent.com/102757126/210977479-20d97e33-9e82-4f5a-bbc0-a59ead5e320c.png)

### Figma design
![image](https://user-images.githubusercontent.com/102757126/210977431-564146f1-c602-498b-bdd1-a204eecb9aa8.png)

2023-01-07 16:48 UTC, binhussen approved these changes
Hi @DamenaM , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions
- Kindly Minimize you modal image size to stick to Figma design 👌👌

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 16:48 UTC, binhussen commented on desktop.css
> +    height: 90%;
- [Optional] Good gob for giving fixed size for your modal image, I think 80% and 90% is high almost your entire screen, I think it is better to minimize it around 50%. 👌👌

2023-01-07 16:56 UTC, merged